feat(best-pratices): disable class methods use this
ovh-ux/eslint-config-ovh pull request #6
Opened 2017-11-29 19:27 UTC by jimmyfortinx

Signed-off-by: Jimmy Fortin <jimmy.fortin@corp.ovh.com>

There is a simple explanation of why I think we should disable this rule:

Since we are using babel (es6) and we are using classes, functions not always using this but are still related and specific to a class. Also, because we are not using any import file system (like requirejs or webpack) we can't write function at the root of the file otherwise those functions will be defined on the global scope and we could have conflit.

There is an example of code if we keep this rule activated:

```javascript
function addStringPrefix(text, prefix) {
    return prefix + text;
}

export class Test {
    constructor(test, test2) {
        this.test = test;
        this.test2 = test2;
    }

    foo() {
        return addStringPrefix(this.test, "test1");
    }

    bar() {
        return addStringPrefix(this.test2, "test2");
    }
}
```

There is an example of code if we disable this rule:

```javascript
export class Test {
    constructor(test, test2) {
        this.test = test;
        this.test2 = test2;
    }

    _addStringPrefix(text, prefix) {
        return prefix + text;
    }

    foo() {
        return this._addStringPrefix(this.test, "test1");
    }

    bar() {
        return this._addStringPrefix(this.test2, "test2");
    }
}
```

2017-11-29 19:54 UTC, mlarose commented
> Also, because we are not using any import file system (like requirejs or webpack) we can't write function at the root of the file otherwise those functions will be defined on the global scope and we could have conflit. (SIC)

Wrapping inside an IIFE could make the function private.

2017-11-29 20:04 UTC, neolitec commented
Yes, we can easily make IIFE with https://github.com/virtyaluk/grunt-iife

2017-11-29 21:15 UTC, jleveugle commented
Hello,



In i keep your example, you can do : 
```javascript
export class Test {
    constructor(test, test2) {
        this.test = test;
        this.test2 = test2;
    }

    static _addStringPrefix(text, prefix) {
        return prefix + text;
    }

    foo() {
        return this._addStringPrefix(this.test, "test1");
    }

    bar() {
        return this._addStringPrefix(this.test2, "test2");
    }
}
```

You can find an example in web manager : Check this : https://github.com/ovh-ux/ovh-manager-web/blob/bb08dc0c75422a40792b01a2943c76ba3ccd59be/client/app/email-domain/email/redirection/update/email-domain-email-redirection-update.controller.js#L24

2017-11-29 21:19 UTC, jleveugle requested changes
Cf my comment ^^

2017-11-30 13:23 UTC, jimmyfortinx commented
@mlarose @neolitec True IIFE could be a solution, what Kevin propose could be enough as a quickwin since the IIFE is ugly.

@jleveugle Good point about static methods, I forgot them. Other point, I didn't knew about the `this.constructor` way to get the class constructor. From the same file you can also write this:

```javascript
foo() {
    return Test._addStringPrefix(this.test, "test1");
}
```

You can also use the `Test._addStringPrefix` when use `import Test from "[...]";`.

Thanks for your feedback!

2017-11-30 13:23 UTC, closed without merging

2017-11-30 14:01 UTC, jleveugle commented
Hello @jimmyfortinx 

Yes, but the syntax Test. is not usable in a view :) ... If you use .constructor, you can use it in view too :p ... It's why we use the syntax .constructor in web manager, to homogenize view / controller :p

But yes, in your case, it's the same :)

2017-12-06 15:38 UTC, neolitec commented
I'll NEVER write `{{constructor.foo()}}` in my templates. Introspection things have nothing to do in templates.

2017-12-06 15:43 UTC, jimmyfortinx commented
@jleveugle Have you something to add to this ? I'm not a big fan of using `*.constructor.*` anyway, so i'm not the good guy to defend the idea to keep this rule enabled.

2017-12-06 15:51 UTC, frenautvh commented
i would do that :

```
export class Test {
    constructor(test, test2) {
        this.test = test;
        this.test2 = test2;
    }

    static _addStringPrefix(text, prefix) {
        return prefix + text;
    }

    foo() {
        return Test._addStringPrefix(this.test, "test1");
    }
}
```

```
<span ng-bind="$ctrl.foo()"></span>
```

2017-12-06 16:06 UTC, jimmyfortinx commented
For this case it could be enough, but it can't be applied on every scenario. Let's try something else:

```javascript
export class Datagrid {
  // this.rows is binded on component using "<"

  [...]

  onClick(currentRow) {
    // do something complex on the clicked row but never use this.
  }
}
```

```html
[...]
<tr ng-repeat="row in $ctrl.rows">
  <td><button ng-click="$ctrl.onClick(row)"></button></td>
</tr>
[...]
```

if we change `onChange` as a static method we are required to write `ng-click="$ctrl.constructor.onClick(row)"` and it is kind weird syntax and the day the controller remove the static flag just because we need the `this` inside method we are required to update all places where we called the method to remove the `.constructor`.