fix(style): allow underscore dangle
ovh-ux/eslint-config-ovh pull request #8
Opened 2017-11-30 18:05 UTC by neolitec

Allow underscore dangle everywhere.

Before, this was not allowed:

```
function (foo) {
    const _foo = foo;
    if (/* a condition on _foo */) {
        _foo = "another_value";
    }
}
```

This rule can be annoying when "no-param-reassign" is also activated because it forces you to find another weird name for your variable.

```
function (foo) {
    const _foo = newFoo;
    if (/* a condition on newFoo */) {
        newFoo = "another_value";
    }
}
```

2017-11-30 18:45 UTC, rfougier approved these changes

2017-12-04 12:55 UTC, jimmyfortinx approved these changes

2017-12-09 09:36 UTC, tremblaymath requested changes
IMHO, for that case, we should prefer to use a new variable name, more descriptive, that correspond to the new value. 

I prefer
```javascript
function (foo) {
    let fooFighters = foo.filter(isFighter)
}
```

To 
```javascript
function (foo) {
    let _foo = foo.filter(isFighter)
}
```
But, I think underscore is fine to differentiate public/private methods

2017-12-11 14:29 UTC, jimmyfortinx commented
@tremblaymath What you describe is not really the same use case that @neolitec described.

I'll try to give you a better, and real, example:

```javascript
// param items can be a single item or an array of items
function showItems(items = []) {
  const _items = angular.isArray(items) ? items : [items];

  _items.forEach(item => console.log(`item: ${item}`))
}
```

How would you name `_items` variable since it is pretty much the same thing but we insure it is an array. Do not forget that we can't do `items = angular.isArray(items) ? items : [items];` because of the `no-param-reassign` rule activated.

2017-12-11 17:24 UTC, tremblaymath commented
Yes I know,  there was not enough context in the first example.
Your example is clear @jimmyfortinx but I think you should prefer throwing an exception to force function consumers to pass the right type or you could use rest operator, if appropriate. IMHO, It complicates the code, without plus value, to support different types for the same parameter.

```javascript
function showItems(...items) {
  _items.forEach(item => console.log(`item: ${item}`))
}
```
I think we should try to refactor the code to avoid it as much as possible.. other examples?

2017-12-11 17:46 UTC, jimmyfortinx commented
@tremblaymath good point, didn't think about the spread operator. 

I think we should wait a real good example before merging, unless everybody is happy with this change.

2018-06-11 05:51 UTC, antleblanc commented
As we are progressly migrate our code to the Airbnb's base configuration, I close this pull request. Feel free to re-open it if needed. We will normally deprecate our ESLint config OVH soon. Thanks.

2018-06-11 05:51 UTC, closed without merging